services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: ${HOSTNAME:-code-server}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PASSWORD=${WEB_PASSWORD}
      - SUDO_PASSWORD=${ROOT_PASSWORD}
      - DEFAULT_WORKSPACE=/projects
      - PWA_APPNAME=${PWA_APPNAME:-code-server}
    volumes:
      - config:/config
      - ${PROJECTS_FOLDER:-./projects}:/projects
    ports:
      - ${PORT:-8443}:8443
    restart: unless-stopped
    networks:
      - net

volumes:
  config:
    name: code-server-config

networks:
  net:
    external: false
