---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PASSWORD=${WEB_PASSWORD}
      - SUDO_PASSWORD=${ROOT_PASSWORD}
      - DEFAULT_WORKSPACE=${WORKSPACE_FOLDER:-./projects}
      - PWA_APPNAME=${PWA_APPNAME:-code_server}
    volumes:
      - ${CONFIG_FOLDER:-./config}:/config
      - ${WORKSPACE_FOLDER:-./projects}:/projects
    ports:
      - ${PORT:-8443}:8443
    restart: unless-stopped

volumes:
  config:
    name: code-server-config

networks:
  net:
    name: code-server-net
    external: false
