services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    hostname: ${HOSTNAME:-code-server}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PASSWORD=${WEB_PASSWORD}
      - SUDO_PASSWORD=${ROOT_PASSWORD}
      - DEFAULT_WORKSPACE=/projects
      - PWA_APPNAME=${HOSTNAME:-code-server}
      - LANG=${LANG:-en_US.UTF-8}
      - LANGUAGE=${LANG:-en_US.UTF-8}
    volumes:
      - ${CONFIG_FOLDER:-./config}:/config
      - ${PROJECTS_FOLDER:-./projects}:/projects
    restart: unless-stopped
    networks:
      net:

networks:
  net: {}
